name: metrics

on:
  schedule:
    - cron: '0 21 * * *'
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: GitHub metrics as SVG image
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}

          # Options
          user: joonas-yoon
          template: classic
          filename: metrics.svg
          base: header, activity, community, repositories, metadata
          config_animated: yes
          config_timezone: Asia/Seoul
          plugin_activity: yes
          plugin_activity_days: 30
          plugin_activity_filter: all
          plugin_activity_limit: 5
          plugin_languages: yes
          plugin_languages_ignored: html, css
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_habits: yes
          plugin_habits_from: 200
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_charts: yes
          plugin_topics: yes
          plugin_topics_mode: mastered
          plugin_topics_limit: 0
          plugin_lines: yes

      - uses: actions/checkout@v2
      - uses: sarisia/actions-readme-feed@v1
        with:
          url: 'https://blog.joonas.io/rss'
          file: 'README.md'
      - run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git add .
          git diff -- dist > git.diff
          [ -s git.diff ] && git add -f . && git commit -m "docs: update feed" && git push || echo "Skip commit"
