name: blog

on:
  schedule:
    - cron: "0 */12 * * *"
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  rss:
    runs-on: ubuntu-latest
    outputs:
      changed: ${{ steps.feed.outputs.changed }}
      items: ${{ steps.feed.outputs.items }}
    steps:
      - uses: actions/checkout@v3
      - name: Fetch rss
        id: feed
        run: |
          pip install requests
          python rss/run.py

      - name: Commit
        run: |
          git config --global user.email "noreply@github.com"
          git config --global user.name "[bot] rss"
          git diff README.md > .diff
          git add README.md
          [ -s .diff ] && git commit -m 'update posts by rss' && git push || echo "No changes"
